vscode:
  extensions:
    - tabnine.tabnine-vscode 

tasks: 
  - name: Persist Tabnine
    init: |
      mkdir /workspace/.tabnine/config -p
      ln -s /workspace/.tabnine/config ~/.config/TabNine
      mkdir /workspace/.tabnine/share
      ln -s .tabnine/share ~/.local/share/TabNine

ports:
  - port: 5555
    onOpen: ignore
