vscode:
  extensions:
    - tabnine.tabnine-vscode 

tasks: 
  - name: Persist Tabnine
    init: |
      mkdir ~/.config -p
      mkdir .tabnine/config -p
      ln -s $GITPOD_REPO_ROOT/.tabnine/config ~/.config/TabNine
      
      mkdir ~/.local/share -p
      mkdir .tabnine/share -p
      ln -s $GITPOD_REPO_ROOT/.tabnine/share ~/.local/share/TabNine

ports:
  - port: 5555
    onOpen: ignore

