name: Enforce PR-Jira association

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  enforce-issue:
    runs-on: ubuntu-stepsecurity-x64
    name: JIRA Association
    steps:
      - name: Check for JIRA ISSUE
        id: check
        uses: usehaystack/jira-pr-link-action@9e164430de66087695e78ac385bbb4f3b2ea61e7 # v5
        with:
          ignore-author: dependabot[bot]
          project: "DEV2"
