name: Tag, Release, & Publish

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Tag
      id: autotagger
      uses: codota/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: npm ci --no-optional
    - name: Package
      run: npm run vsce:package
    - name: Create Release
      id: create_release
      if: steps.autotagger.outputs.tagname != ''
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.autotagger.outputs.tagname }}
        release_name: Release ${{ steps.autotagger.outputs.tagname }}
        draft: false
        prerelease: ${{ steps.autotagger.outputs.prerelease == 'yes' }}
    - name: Upload Release Asset
      id: upload-release-asset 
      if: steps.autotagger.outputs.tagname != ''
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_name: tabnine-vscode.vsix
        asset_path: ./tabnine-vscode-${{ steps.autotagger.outputs.tagname }}.vsix
        asset_content_type: application/octet-stream
    - name: Publish
      if: steps.autotagger.outputs.tagname != ''
      run: npm run vsce:publish -- ${{ steps.autotagger.outputs.tagname }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}