name: Update Binaries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 0'

jobs:
  update:
    name: Update Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch current binaries versions
        run: ./dl_binaries.sh
      - name: Create Pull Request
        id: cpr
        uses: codota/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: Update Binaries
          branch: update-binaries
          delete-branch: true
          title: '[Bot] Update Binaries'
          labels: |
            binaries
            automated pr
          assignees: dimacodota
          team-reviewers: |
            owners
            maintainers
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"