name: Validate Marketplace

on:
  release:
    types: [released]
  
jobs:
  run:
    runs-on: ubuntu-stepsecurity-x64
    steps:
    - uses: codota/wait-action@master
      with:
        time: '5m'
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: codota/visual-regression@master
      with:
        url: https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode
        screenshotFilename: marketplace-screenshot
        slackWebhook: ${{ secrets.SLACK_VALIDATE_MARKETPLACE_WEBHOOK }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}